apiVersion: apps/v1
kind: Deployment
metadata:
  name: gv-ui
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: gv-ui
  template:
    metadata:
      labels:
        app: gv-ui
    spec:
      containers:
        - image: wiracochamanager/mirepo:ee934d3af277bcd523992db5f5f002a6cb0e8285
          name: gv-ui
          ports:
            - containerPort: 80
