apiVersion: apps/v1
kind: Deployment
metadata:
  name: gv-ui
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: gv-ui
  template:
    metadata:
      labels:
        app: gv-ui
    spec:
      containers:
        - image: wiracochamanager/mirepo:80391f1a3caa7c39e542c25ea2cdc630b9826cee
          name: gv-ui
          ports:
            - containerPort: 80
