apiVersion: apps/v1
kind: Deployment
metadata:
  name: gv-ui
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: gv-ui
  template:
    metadata:
      labels:
        app: gv-ui
    spec:
      containers:
        - image: wiracochamanager/mirepo:a8a5626d95f199741c73347dedfbdab5433fb20f
          name: gv-ui
          ports:
            - containerPort: 80
