apiVersion: apps/v1
kind: Deployment
metadata:
  name: gv-ui
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: gv-ui
  template:
    metadata:
      labels:
        app: gv-ui
    spec:
      containers:
        - image: wiracochamanager/mirepo:41da99ea78666c134bb2345825c461002e16cb51
          name: gv-ui
          ports:
            - containerPort: 80
