apiVersion: apps/v1
kind: Deployment
metadata:
  name: gv-ui
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: gv-ui
  template:
    metadata:
      labels:
        app: gv-ui
    spec:
      containers:
        - image: wiracochamanager/mirepo:8ccd752c9fd8932b42a76831e058837992d98083
          name: gv-ui
          ports:
            - containerPort: 80
